# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: spyre.ibm.com/v1alpha1
kind: SpyreClusterPolicy
metadata:
  name: spyreclusterpolicy
spec:
  devicePlugin:
    repository: "ghcr.io/ibm-aiu"
    image: "spyre-device-plugin"
    version: 1.4.0-dev
    configPath: /etc/aiu
    configName: senlib_config.json
    initContainer:
      repository: "ghcr.io/ibm-aiu"
      image: "spyre-device-plugin-init"
      version: 1.4.0-dev
      executePolicy: IfNotPresent
      runtime:
        repository: quay.io/ibm-aiu
        image: spyre-runtime
        version: 1.3.0
  scheduler:
    repository: "ghcr.io/ibm-aiu"
    image: "spyre-scheduler"
    version: 1.4.0-dev
  podValidator:
    enabled: true
    repository: "ghcr.io/ibm-aiu"
    image: "spyre-webhook-validator"
    version: 1.4.0-dev
  metricsExporter:
    enabled: true
    repository: "ghcr.io/ibm-aiu"
    image: "spyre-exporter"
    version: 1.4.0-dev
  healthChecker:
    enabled: true
    repository: "ghcr.io/ibm-aiu"
    image: "spyre-health-checker"
    version: 1.4.0-dev
  experimentalMode:
  - externalDeviceReservation
  - perDeviceAllocation
  - topologyAwareAllocation
